name: Check PR for non-docs files

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-docs-only:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Check modified files
      run: |
        # 获取修改的文件列表
        MODIFIED_FILES=$(git diff --name-only origin/main)
        # 检查是否有非 /docs/ 目录的文件被修改
        if echo "$MODIFIED_FILES" | grep -qvE '^docs/'; then
          echo "Detected non-docs files changed!"
          # 提醒提交者
          gh pr comment "$GITHUB_REF" -b "⚠️ PR contains changes outside of the /docs/ directory. Please limit your changes to the /docs/ folder."
          # 关闭 PR
          gh pr close "$GITHUB_REF" -r "PR contains changes outside of /docs/ directory."
        else
          echo "Only /docs/ files were modified."
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
